cdname: Publish Docker image to Docker Hub

on:
  push:
    branches:
      - dockerfile
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

      - name: Build and push Docker image
        run: |
          docker build -t Popolato/docker_DataFrame ./pandas
          docker push Popolato/docker_DataFrame
