# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      # Testing phase
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots verify -f panda/pom.xml
      # Store jacoco.xml Into A New Folder
      - name: Put into a directory
        run: |
              mkdir target
              cd ./target
              mkdir site
              cd ./site
              mkdir jacoco && cd ../..
              cp panda/target/site/jacoco/jacoco.csv target/site/jacoco
              ls -r target/site/jacoco
      #Upload the results.xml as an artifact
      - name: Archive Code Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: target/site/jacoco
  
  test_coverage:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      # Dowload the results to exploit
      - name: Download Code Coverage Results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: target/site/jacoco
      # Check the root of the repo
      - name : Display root
        run: ls -r target/site/jacoco
        
        
      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Commit and push the coverage badges and summary file
        run: |
          cd badges
          if [[ `git status --porcelain *.svg *.json` ]]; then
            git config --global $GITHUB_ACTOR 'github-actions'
            git config --global $GITHUB_ACTOR_EMAIL '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.svg *.json
            git commit -m "Autogenerated JaCoCo coverage badges" *.svg *.json
            git push
          fi

      - name: Comment on PR with coverage percentages
        run: |
          REPORT=$(<badges/coverage-summary.json)
          COVERAGE=$(jq -r '.coverage' <<< "$REPORT")%
          BRANCHES=$(jq -r '.branches' <<< "$REPORT")%
          NEWLINE=$'\n'
          BODY="## JaCoCo Test Coverage Summary Statistics${NEWLINE}* __Coverage:__ ${COVERAGE}${NEWLINE}* __Branches:__ ${BRANCHES}"
          gh pr comment ${{github.ref}} -b "${BODY}"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


